version: '3.8'

x-logging: &loki-logging
    driver: loki
    options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,maintainer=xylonx,environment=development
        loki-pipeline-stages: |
            - json:
                expressions:
                    traceId: TraceID
                    spanId: SpanID
                    level: level
            - labels:
                traceId:
                spanId:
                level:

services:
  recruitment_backend2023:
    build: .
    container_name: recruitment_backend_2023
    ports:
      - "3333:3333"
    volumes:
      - "./data/logs:/app/data/logs"  #日志
      - "./data/resumes:/app/data/resumes" #简历
    networks:
      - database
      - apm
    
    logging: *loki-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hr2023-back-dev.rule=Host(`dev.back.recruitment2023.hustunique.com`)"

networks:
  database:
    external: true
  apm:
    external: true
